---
title: "Wiederholungsübung"
author: "Ihr Name"
date: "18.12.2019"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(mosaic)
```

# Fragestellung

<!-- Hinweise: Sollten die Umlaute nicht richtig dargestellt werden: Menü: File -> Reopen with Encoding -> UTF-8 -->

Wie hängt die Produktion (`produktion`) innerhalb einer chemischen Reaktion von der Zeit (`zeit`) und der Temperatur (`temperatur`) ab? Welche Zeit/ Temperatur Kombination führt zu einer maximalen Produktion?

Um den Effekt von Kovariablen zu reduzieren wurden die Versuche in zwei verschiedenen Blöcken (`block`) durchgeführt.

## Daten

```{r}
zeit <- c(80, 80, 90, 90, 85, 85, 85, 85, 85, 85, 92.07, 77.93, 85, 85)
temperatur <- c(170, 180, 170, 180, 175, 175, 175, 175, 175, 175, 175, 175, 182.07, 167.93)
block <- factor(c("B1", "B1", "B1", "B1", "B1", "B1", "B1", "B2", "B2", "B2", "B2", "B2", "B2", "B2"))
produktion <- c(80.5, 81.5, 82, 83.5, 83.9, 84.3, 84, 79.7, 79.8, 79.5, 78.4, 75.6, 78.5, 77)

ChemReak <- data.frame(block, zeit, temperatur, produktion)
```

# Auswertung

```{r}

```


